### PR TITLE
Wysiwyg

### PR DESCRIPTION
**Pull request by wesobi**
Added WYSIWYG editor for text-areas where markdown is allowed
(added js, sass, changed views and added font-awesome for the icons).

Fix for #33?

### CODE REVIEW

**Comment by ghost** [comment]
I have to make a few small changes (WYSIWYG is missing on page edit for example) and I'll merge it myself into develop, so I'm closing this pull request. Thanks for the editor & hamburger menu.

**Comment by wesobi** [comment]
@u-nico For some reason the edit-pages is not working locally after going through the installation again. I'm going through the logs to check if I did something wrong during installation or there is another issue, hence why I did not add it there (to not break those pages). Will make a new issue if I can not seem to figure it out though.

**Comment by ghost** [comment]
Well yeah, didn't your migrations fail in #66? I'm looking into that next.

**Comment by ghost** [comment]
The pages should be seeded before they start working. Did you seed `DefaultPagesSeeder`? If you didn't, that explains why it doesn't work on your end.

**Comment by wesobi** [comment]
Yes, that did it. Might be a good idea to edit the SETUP.md page to include seeding the DefaultPagesSeeder? Going off topic though.

**Comment by ghost** [comment]
I'll add it to the SETUP markdown file.

**Pull request closed without merging**
